apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "homebridge.fullname" . }}
  labels:
    app: {{ template "homebridge.name" . }}
    chart: {{ template "homebridge.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "homebridge.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "homebridge.name" . }}
        release: {{ .Release.Name }}
      {{- with .Values.annotations }}
      annotations:
      {{ toYaml . | indent 8 }}
      {{- end }}
    spec:
      volumes:
{{ toYaml .Values.volumes | indent 6 }}
      hostNetwork: true
      dnsPolicy: ClusterFirst
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: HOMEBRIDGE_CONFIG_UI
              value: '1'
            - name: HOMEBRIDGE_CONFIG_UI_PORT
              value: "{{ .Values.config_ui_port }}"
            - name: HOMEBRIDGE_INSECURE
              value: '1'
{{ toYaml .Values.env | indent 12 }}
          ports:
            - name: homebridge
              containerPort: 51827
              protocol: TCP
            - name: homebridge-ui
              containerPort: {{ .Values.config_ui_port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.config_ui_port }}
            timeoutSeconds: 30
            initialDelaySeconds: 300
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.config_ui_port }}
            timeoutSeconds: 30
          volumeMounts:
{{ toYaml .Values.volumeMounts | indent 12 }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
