
replicaCount: 1

image:
  repository: linuxserver/nzbhydra2
  tag: latest
  pullPolicy: IfNotPresent

env:
  - name: PUID
    value: "1000"
  - name: PGID
    value: "1000"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - nzbhydra.patrickjmcd.org
  tls:
   - secretName: nzbhydra-patrickjmcd-org
     hosts:
       - nzbhydra.patrickjmcd.org

volumes:
  - name: myvolume
    persistentVolumeClaim:
      claimName: myvolume

volumeMounts:
  - name: myvolume
    mountPath: "/config"
    subPath: "configs/nzbhydra"
  

resources:
  requests:
    memory: 128Mi
    cpu: 0.1
  limits:
    memory: 256Mi
    cpu: 0.5

nodeSelector: {}

tolerations: []

affinity: {}
